name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  webUI:
    runs-on: ubuntu-latest # 编译环境

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: 列出仓库，目录  # 进入前端项目仓库
        run: ls
      - name: 进入前端项目目录  # 进入前端项目
        run: cd /home/runner/work/Destiny.Core.Flow.WebUI/Destiny.Core.Flow.WebUI/destiny-admin-flow-vue && yarn install && yarn build    # build WebUI Project 
    
      - name: copy config to dist  # 拷贝文件进入dist目录
        run: cp /home/runner/work/Destiny.Core.Flow.WebUI/Destiny.Core.Flow.WebUI/destiny-admin-flow-vue/nginx.conf /home/runner/work/Destiny.Core.Flow.WebUI/Destiny.Core.Flow.WebUI/destiny-admin-flow-vue/Dockerfile /home/runner/work/Destiny.Core.Flow.WebUI/Destiny.Core.Flow.WebUI/destiny-admin-flow-vue/dist/
      - name: 列出打包后的目录
        run: ls /home/runner/work/Destiny.Core.Flow.WebUI/Destiny.Core.Flow.WebUI/destiny-admin-flow-vue/dist # Project path in github 
      - name: 登录docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          tags: 18790997531/destinycoreweb:latest
          push: true
          context: Destiny.Core.Flow.WebUI/destiny-admin-flow-vue/dist 
          file: Destiny.Core.Flow.WebUI/destiny-admin-flow-vue/dist/Dockerfile # Build docker Image
    
