# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest # 编译环境

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: cd /destiny-admin-flow-vue  # 进入前端根目录
        run: cd /destiny-admin-flow-vue

      - name: cd /destiny-admin-flow-vue  # 进入前端根目录
        run: cd /destiny-admin-flow-vue

      - name: 列出目录  # 进入前端根目录
        run: ls

      - name: yarn install  # 安装npm 包
        run: yarn install
    
      - name: yarn build  # 打包前端项目
        run: yarn build

      - name: copy config to dist  # 拷贝文件进入dist目录
        run: cp nginx.conf Dockerfile dist/

      - name: build image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 18790997531/destinycoreweb
          tags: latest
          path: /home/runner/work/Destiny.Core.Flow.WebUI/Destiny.Core.Flow.WebUI/destiny-admin-flow-vue/dist
          dockerfile: /home/runner/work/Destiny.Core.Flow.WebUI/Destiny.Core.Flow.WebUI/destiny-admin-flow-vue/Dockerfile
    
